# Top-level settings
add_newline = false
command_timeout = 1000
palette = "catppuccin_mocha"

# Only show modules you want in specific order
format = """$hostname $directory $character"""
# move the rest of the prompt to the right
#right_format = """$all"""
#right_format = """$git_branch $git_status $python $cmd_duration $time"""
right_format = """$git_branch $git_status"""

[hostname]
ssh_only = false
format = "\\[[$hostname](${style})\\]"
style = "bold green"
ssh_symbol = "🔗 "
trim_at = ""

[directory]
truncation_length = 10
truncation_symbol = '../'
truncate_to_repo = true

[directory.substitutions]
'/global/projects/pequin' = 'pequin'

[character]
success_symbol = '[⟩](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[⟨](bold green)'
vimcmd_replace_one_symbol = '[⟨](bold purple)'
vimcmd_replace_symbol = '[⟨](bold purple)'
vimcmd_visual_symbol = '[⟨](bold yellow)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'bold purple'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'bold yellow'
staged = '[+\($count\)](green)'
modified = '[~\($count\)](yellow)'
deleted = '[-\($count\)](red)'
untracked = '[?\($count\)](blue)'
conflicted = '[x\($count\)](red)'
ahead = '⇡($count)'
behind = '⇣($count)'
diverged = '⇕($count)'
up_to_date = "✅"

# Palette definition
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

